### ISSUE TITLE
Default configuration, successful installation, some error lines appeared on the top of the page

### ISSUE THREAD

**Issue by themedleb** [choquo/fresh-wp#1]
I tried the plugin in a local machine using Local by Flywheel, I left everything in the plugin with the default configuration, theme and plugins untouched, the installation went successfully as the plugin said, but It has some error lines on the top of the page:

`Warning: unlink(wp-content/plugins/zipfile72.zip): Text file busy in /app/public/fresh.php on line 90 Warning: unlink(wp-content/plugins/zipfile43.zip): Text file busy in /app/public/fresh.php on line 90 Warning: unlink(wp-content/plugins/zipfile69.zip): Text file busy in /app/public/fresh.php on line 90 Warning: unlink(wp-content/plugins/zipfile94.zip): Text file busy in /app/public/fresh.php on line 90 Warning: unlink(wp-content/plugins/zipfile14.zip): Text file busy in /app/public/fresh.php on line 90 Warning: unlink(wp-content/plugins/zipfile12.zip): Text file busy in /app/public/fresh.php on line 90 Warning: unlink(wp-content/plugins/zipfile67.zip): Text file busy in /app/public/fresh.php on line 90 Warning: unlink(wp-content/plugins/zipfile67.zip): Text file busy in /app/public/fresh.php on line 90 Warning: unlink(wp-content/plugins/zipfile5.zip): Text file busy in /app/public/fresh.php on line 90 Warning: unlink(wp-content/plugins/zipfile53.zip): Text file busy in /app/public/fresh.php on line 90 Warning: unlink(wp-content/themes/zipfile38.zip): Text file busy in /app/public/fresh.php on line 134`

Is there anything that went wrong or it's normal?

**Comment by choquo** [comment]
@themedleb  Can you check if the temp files is still there? for example the file: wp-content/plugins/zipfile43.zip should be deleted after the unzip, if the file is still there maybe it's a problem of write permissions on your computer, you should grant write permissions to the folder, but if the log throws a warning then is not a problem you just need to check the things mentioned before.

**Comment by themedleb** [comment]
@choquo Yes all the 9 temp files are still there (from zipfile5.zip to zipfile94.zip), but all the plugins and theme are installed successfully.

**Comment by choquo** [comment]
@themedleb can you download again the files and try? I have made some changes, let me know if now delete the temp files.

**Comment by themedleb** [comment]
After trying the new version, no single warning and no temp files left, well done and thank you.

**Comment by themedleb** [comment]
I'm (and other people that know about this plugin) really excited about the coming UI.
